"""
Security Validation for CLI
---------------------------
This module provides security validation functions to prevent insecure patterns
from being generated by the CLI scaffolding tools.
"""

import keyword
import re

PYTHON_IDENTIFIER_RE = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_]*$")

# Dangerous field names that should not be allowed in user-generated models
DANGEROUS_FIELD_NAMES = {
    "is_superuser",
    "is_admin",
    "is_staff",
    "is_staff_user",
    "is_administrator",
    "has_admin_access",
    "admin",
    "superuser",
    "super_user",
    "root",
    "password_hash",
    "hashed_password",
    "secret_key",
    "api_key",
    "access_token",
    "refresh_token",
    "token",
}

# Dangerous resource names that should not be allowed
DANGEROUS_RESOURCE_NAMES = {
    "user",
    "admin",
    "adminuser",
    "admin_user",
    "superuser",
    "permission",
    "role",
    "token",
    "auth",
    "security",
}

# Reserved module paths that should not be used
RESERVED_MODULE_PATHS = {
    "swx_core.models",
    "swx_core.auth",
    "swx_core.security",
    "swx_core.rbac",
}


def validate_field_name(field_name: str) -> tuple[bool, str | None]:
    """Validates that a field name is not dangerous, reserved, or invalid."""
    field_lower = field_name.lower().strip()

    if not PYTHON_IDENTIFIER_RE.match(field_name):
        return False, f"Field name '{field_name}' is not a valid Python identifier."

    if keyword.iskeyword(field_name):
        return False, f"Field name '{field_name}' is a Python reserved keyword."

    if field_lower in DANGEROUS_FIELD_NAMES:
        return False, f"Field name '{field_name}' is reserved for security reasons. Use a different name."

    if field_lower.startswith("is_") and any(
        keyword in field_lower for keyword in ["admin", "super", "staff", "root"]
    ):
        return False, f"Field name '{field_name}' suggests privilege escalation. Use RBAC permissions instead."

    if "password" in field_lower and field_lower != "password":
        return False, f"Field name '{field_name}' suggests password handling. Use framework's password security utilities."

    if "token" in field_lower or "secret" in field_lower or "key" in field_lower:
        return False, f"Field name '{field_name}' suggests sensitive data. Use framework's security utilities."

    return True, None


def validate_resource_name(resource_name: str) -> tuple[bool, str | None]:
    """Validates that a resource name is not dangerous, reserved, or invalid."""
    resource_lower = resource_name.lower().strip()

    if not PYTHON_IDENTIFIER_RE.match(resource_name):
        return False, f"Resource name '{resource_name}' is not a valid Python identifier."

    if keyword.iskeyword(resource_name):
        return False, f"Resource name '{resource_name}' is a Python reserved keyword."

    if resource_lower in DANGEROUS_RESOURCE_NAMES:
        return False, f"Resource name '{resource_name}' is reserved. Use a different name."

    if resource_lower in ["auth", "security", "rbac", "permission", "role"]:
        return False, f"Resource name '{resource_name}' conflicts with framework security modules. Use a different name."

    return True, None


def validate_module_path(module_path: str) -> tuple[bool, str | None]:
    """Validates that a module path is not reserved and has no path traversal."""
    if ".." in module_path or "/" in module_path or "\\" in module_path:
        return False, f"Module path '{module_path}' contains path traversal characters."

    if module_path in RESERVED_MODULE_PATHS:
        return False, f"Module path '{module_path}' is reserved for framework use. Use 'swx_app.models' or your own app namespace."

    if module_path.startswith("swx_core."):
        return False, f"Module path '{module_path}' is in framework code. Use 'swx_app.models' or your own app namespace."

    return True, None


def validate_columns(columns: list[tuple[str, str]]) -> tuple[bool, str | None]:
    """Validates all column names in a list."""
    for field_name, _ in columns:
        is_valid, error = validate_field_name(field_name)
        if not is_valid:
            return False, error
    return True, None
